language: python
python:
  - '2.7'
dist: precise

before_install:
  - pip install awscli
  - scripts/travis_install_apex.sh

install:
  - pip install -r requirements.txt
  - pip install coveralls

script: coverage run test-setup.py test

after_success:
  - coveralls

env:
  global:
    - PYTHONDONTWRITEBYTECODE=true

deploy:
- provider: script
  skip_cleanup: true
  script:
  - scripts/deploy.sh && scripts/register_modules.sh https://dev-api.door43.org && scripts/integration_test.sh
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script:
  - scripts/deploy.sh && scripts/register_modules.sh https://api.door43.org && scripts/integration_test.sh
  on:
    branch: master

